### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by legion49f** [WebexSamples/hookbuster#8] opened 2022-12-13 14:56 UTC
I have built hookbuster into a containerized application and have had the container crash with this trace back a few times. 

failed to execute Logger#warn RangeError: Maximum call stack size exceeded
hookbuster_1  |     at walkAndFilter (/node_modules/@webex/plugin-logger/dist/logger.js:92:23)
hookbuster_1  |     at walkAndFilter (/node_modules/@webex/plugin-logger/dist/logger.js:122:23)

Any help will be appreciated. I am not a JS developer unfortunately but i have some inclination that this might be due to a recursion loop.

Thanks in advance!

**Comment by jbenyovs** [comment] 2022-12-15 14:05
@legion49f not sure how to reproduce this, would you mind describing the exact steps? Generally "Maximum call stack size exceeded" would happen if you are calling a function over and over again until the call stack size is reached. So yes, like a recursion loop, that cannot stop for some reason. I don't think that the hookbuster app has any recursions built in, but if you have the exact steps and infrastructure needed to reproduce this, I might take a closer look.

**Comment by legion49f** [comment] 2022-12-23 16:45
Sure, we have built hookbuster into a container image which is now merged to master and this happens when the container image is left running for over a period of time. The steps to reproduce are just to leave hookbuster running for some time. It's worth pointing out that this might be an issue with the WebEx logger plugging imported by hookbuster and not an issue with the code from this application.

**Comment by jbenyovs** [comment] 2023-02-01 10:40
@legion49f  thanks, I replied to the ticket and got in touch with JS SDK engineering internally and added you to the conversation.

**Comment by jbenyovs** [comment] 2023-05-08 11:51
Since the conversation was moved to an internal Webex space, closing this issue. The error was coming from a JS SDK function, not the hookbuster.

**Closed by jbenyovs** 2023-05-08 11:51 UTC
